config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('res/', include('res.urls')),
    # path('member/', include('member.urls')),
]

edu/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'edu'
urlpatterns = [
    path("index/<int:pg>", views.index),
    path("detail/<int:edu_seq>", views.edu_detail),
    # path("write", views.write),
    # path("save", views.save),
    path("main",views.main),
    path('edu/delete/<int:edu_seq>', views.delete),
]

res/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'res'

urlpatterns = [
    path('main/', views.main, name='main'),
    path('index/<int:pg>/', views.res_index, name='index'),
    path('detail/<int:res_seq>/', views.res_detail),
    path('join/', views.res_join_form),
    path('save/', views.res_join_save, name='join_save'),
    path('write/', views.write, name='write'),
    path('write_save/', views.write_save, name='write_save'),
    path('logon/', views.logon, name='logon'),
    path('logout/', views.logout, name='logout'),
    path('deletepost/', views.deletepost, name='deletepost/'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

res/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Member(models.Model):
    mem_seq = models.FloatField(primary_key=True)
    mem_id = models.CharField(max_length=200)
    mem_password = models.CharField(max_length=200)
    mem_google_id = models.CharField(max_length=200, blank=True, null=True)
    mem_naver_id = models.CharField(max_length=200, blank=True, null=True)
    mem_type = models.CharField(max_length=200)
    mem_age = models.FloatField()
    mem_name = models.CharField(max_length=200)
    mem_wdate = models.DateField()
    mem_update = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'member'


class Restaurant(models.Model):
    res_seq = models.FloatField(primary_key=True)
    mem_seq = models.ForeignKey(Member, models.DO_NOTHING, db_column='mem_seq')
    res_name = models.CharField(max_length=200)
    res_locate = models.CharField(max_length=200)
    res_phone = models.CharField(max_length=200)
    res_content = models.CharField(max_length=200, blank=True, null=True)
    res_score = models.FloatField(blank=True, null=True)
    res_hit = models.FloatField()
    res_wdate = models.DateField()
    res_update = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'restaurant'

res/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.db import connection
from res.resUtil import dictfetchall
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import auth, messages
from django.contrib.auth.hashers import check_password
from common.CommonUtils import dictfetchall, commonPage

# Create your views here.
# 메인 페이지
# django에서 session 값을 저장해두는 공간이 필요한데
# 처음 django-admin startproejct 하고 migrate를 한번도 하지 않으면
# 저장해줄 공간이 없다고 나옴
# 따라서 models.py와 관계없이 기본적으로 migrate가 한번 이루어져야함
def main(request):
    userid = request.session.get('user', '') # 메인 페이지 불러올 때 세션에 user(로그인한 아이디) 할당
    memseq = request.session.get('mem_seq', '') # 메인 페이지 불러올 때 세션에 mem_seq(로그인한 사람 seq) 할당
    context = {
        'userid':userid,
        'memseq':memseq
    }
    return render(request, 'res/main.html', context)

# 게시글 리스트 페이지
def res_index(request, pg):
    cursor = connection.cursor()
    sql = "select count(*) from restaurant"
    cursor.execute(sql)
    totalCnt = int(cursor.fetchone()[0])
    
    search_tag = request.GET.get('search', '')
    cp = commonPage(totalCnt, pg, 10)

    # 리스트 불러오고 페이징 처리
    # where문에 조건 2개 사용한 or 이 아닌
    # select 문 2개 생성 후 각각 where 조건을 주고 UNION으로 합쳤다면 
    # 검색 쿼리가 정상적으로 작동했을지도?
    sql = f"""
        select A.mem_seq, A.res_seq, A.res_name, A.res_score, A.res_hit, 
            to_char(A.res_wdate, 'yyyy-mm-dd') res_wdate, A.mem_id, num
        from 
        (
            select  A.mem_seq, A.res_seq, A.res_name, 
                    A.res_score, A.res_hit, 
                    A.res_wdate, B.mem_id,
                    row_number() over(order by A.res_hit desc) num,
                    ceil(row_number() over(order by A.res_hit desc)/10)-1 pg
            from restaurant A 
            left outer join member B on A.mem_seq=B.mem_seq
            where A.res_name like '%{search_tag}%' or
            B.mem_id like '{search_tag}'
        

            -- 검색 조건 필요할 경우에 여기에
        ) A
        where A.pg={pg}
    """
    
    cursor.execute(sql)
    
    # sql을 활용하여 가져온 게시글 리스트 할당
    resList = dictfetchall(cursor)
    context = {}

    # 로그인 상태를 구분할 수 있도록 세션에 값 할당
    userid = request.session.get('user', '')
    memseq = request.session.get('mem_seq', '')
    context['memseq'] = memseq
    context['userid'] = userid

    context['resList'] = resList
    context['commonPage'] = cp
    return render(request, "res/res_index.html", context)

# 게시글 상세 페이지
def res_detail(request, res_seq):
    
    cursor = connection.cursor()

    # 게시글 클릭 시 조회수 1씩 증가하는 쿼리
    sql = f"""update restaurant set res_hit = res_hit +1 where res_seq = {res_seq}"""
    cursor.execute(sql)

    # 가게의 상세정보를 위한 가게 1개 조회
    sql = f"""
    select mem_seq, res_name, res_locate, res_phone, res_content,  res_score, res_hit, res_wdate
    from restaurant
    where res_seq = {res_seq}
    """
    cursor.execute(sql)
    resInfo = dictfetchall(cursor)[0]
    
    # 가게의 메뉴 조회
    sql = f"""
    select res_item_title, res_item_content, res_item_pic, res_item_price
    from res_item
    where res_seq = {res_seq}
    """
    cursor.execute(sql)
    menuList = dictfetchall(cursor)

    # 가게에 작성한 리뷰들 조회
    sql = f"""
    SELECT mem.mem_id, rev.res_review_title, rev.res_review_content,
    rev.res_review_wdate, rev.res_review_rating
    FROM res_review rev
        JOIN restaurant res
        ON rev.res_seq = res.res_seq
    INNER JOIN member mem
        ON res.mem_seq = mem.mem_seq
    where res.res_seq = {res_seq}
    """
    cursor.execute(sql)
    reviewList = dictfetchall(cursor)
    memseq = request.session.get('mem_seq', '')

    # 로그인
    userid = request.session.get('user', '')
    memseq = request.session.get('mem_seq', '')

    return render(request, 'res/res_detail.html',  
                  {'resInfo':resInfo, "menuList":menuList, 'reviewList':reviewList, 'memseq': memseq, 'userid':userid})
    
# 회원가입 페이지로 이동
def res_join_form(request):
    return render(request, 'res/res_join_form.html')

# 회원가입 데이터 저장 쿼리
def res_join_save(request):

    mem_id = request.POST.get('mem_id')
    password = request.POST.get('pwd')
    age = request.POST.get('age')
    name = request.POST.get('name')
    cursor = connection.cursor()

    sql = f"""
    insert into member (
    mem_seq, mem_id, mem_password, mem_google_id, mem_naver_id, mem_type, mem_age, mem_name, mem_wdate, mem_update)
    values(mem_seq.NEXTVAL, '{mem_id}', '{password}', 'N', 'N', 1, '{age}', '{name}', sysdate, sysdate)
    """  

    cursor.execute(sql)
    connection.commit()  
    # redirect 사용시 세션값을 지정해줄 필요 x
    return redirect('res:main')

# 글쓰기 페이지로 이동
def write(request):
    userid = request.session.get('user', '')
    memseq = request.session.get('mem_seq', '')
    context = {
        'userid':userid,
        'memseq':memseq
    }
    return render(request, 'res/res_write.html', context)

# 게시글 작성 
def write_save(request):

    # 게시글 작성자가 필요하므로 mem_seq 가져와야함 (작성자 회원정보에서)
    memseq = request.session.get('mem_seq', '')
    title = request.POST.get('title')
    address = request.POST.get('address')
    phone = request.POST.get('phone')
    content = request.POST.get('content')

    cursor = connection.cursor()
    sql = f"""
    insert into restaurant (res_seq, mem_seq, res_name, res_locate, res_phone, res_content, res_hit, res_wdate)
    values (res_seq.NEXTVAL,{memseq}, '{title}', '{address}', '{phone}', '{content}', 0, sysdate)
    
    """
    cursor.execute(sql)
    connection.commit()
    return redirect('res:index', pg=0)

from django.db.models import Q
from res.models import Member
# 로그인
def logon(request):
    # GET 방식으로 접근할 경우 로그인 안받음
    if request.method == 'GET':
        return render(request, 'res:main')
    
    # POST 방식으로 접근하면 입력한 로그인과 비밀번호 받기
    elif request.method == 'POST':
        userid = request.POST.get('logonid',None)
        password = request.POST.get('logonpw',None)
        res_data = {}
        
        # 테이블에는 중복값을 허용하지만 원래는 아이디가 중복 불가이므로 아이디로 
        # 회원정보 조회
        cursor = connection.cursor()
        sql = f"""select mem_seq from member where mem_id = '{userid}'"""
        cursor.execute(sql)
        memdict = dictfetchall(cursor)
        # [{데이터}] 형태이므로 인덱싱
        mem_seq = memdict[0]['mem_seq']

        if not (userid and password):
            res_data['error'] = '모든 값을 입력해야 합니다.'
        else:
            # 아이디와 비밀번호가 일치하는 데이터를 찾기 위해 검색 조건 생성
            q1 = Q(mem_id=userid)
            q2 = Q(mem_password=password)

            # 아이디, 비밀번호 둘 다 일치하는 데이터가 존재할 때
            # 세션에 값 할당함
            if len(Member.objects.filter(q1 & q2)) > 0:
                request.session['user'] = userid
                request.session['mem_seq'] = mem_seq
                # request.set_cookie('user', userid)
                return redirect('res:main') 
            
            else:
                res_data['error'] = '정보가 일치하지 않습니다'
            
            # 로그인 실패 및 오류메세지와 함께 응답
            return render(request, 'res:main', res_data)
        
# 로그아웃 버튼을 누를 경우 세션 값 삭제함
def logout(request):
    del request.session['user']
    return redirect('res:main')

# 게시글 삭제
# 그대로 실행시 게시글을 모두 삭제함
# 추가로 게시글 title을 불러와서 where문 조건에 추가 필요할 듯
def deletepost(request):
    userid = request.session.get('user', '')
    memseq = request.session.get('mem_seq', '')
    context = {}
    context['userid'] = userid
    context['memseq'] = memseq
    cursor = connection.cursor()
    sql = f"""
    delete from restaurant where mem_seq = '{memseq}'"""
    cursor.execute(sql)
    connection.commit()
    messages.success(request, '게시글이 성공적으로 삭제되었습니다.')
    return redirect("res:index", pg=0)

templates/res/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Page</title>
    <style>
        
        @font-face {
        font-family: 'SUITE-Regular';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2304-2@1.0/SUITE-Regular.woff2') format('woff2');
        font-weight: 400;
        font-style: normal;
    }
        body {
            font-family:'SUITE-Regular'
        }
        .container {
            font-family: 'SUITE-Regular';
            font-weight: 100;
            position: absolute;
            top: 15%;
            left: 33%;
        }
        .btns {
            font-family: 'SUITE-Regular';
            font-weight: 200;
            width: 70px;
            height: 30px;
            border-radius: 30px;
            border-color: rgb(214, 211, 211);
            border-style: solid;
            margin-right: 20px ;
            transition-property: background-color;
            transition-timing-function: ease-in;
            transition-duration: 0.2s;
            font-size: 1em;
        }
        .btns:hover {
            background-color: black;
            color: white;
        }
        .main_item {
            width: 250px;
            height: 250px;
            display: inline-flex;
            margin: 0;
            background-color: rgb(195, 191, 191);
            color: white;
            justify-content: center;
            align-items: center;
            font-size: 2.5em;
            transition-property: border-radius, background-color;
            transition-timing-function: ease-in;
            transition-duration: 0.5s;
        }
        .main_item:hover {
            border-radius: 30%;
            background-color: gray;
        }
        .main_item2 {
            width: 250px;
            height: 250px;
            display: inline-flex;
            margin-top: 5px;
            background-color: rgb(206, 202, 202);
            
            color: white;
            justify-content: center;
            align-items: center;
            font-size: 2.5em;
            transition-property: border-radius, background-color;
            transition-timing-function: ease-in;
            transition-duration: 0.5s;
        }
        .main_item2:hover {
            border-radius: 30%;
            background-color: gray;
        }
        .logondiv {
            margin-top: 3px;
        }
        input {
            width:100px;
            margin-right:5px;
            margin-top: 5px;
            border-radius: 5px;
        }
    </style>
        
   
</head>
<body>
    
    <div style="float: right;" class="logondiv">
        
        {% if userid %}
        <button style="float: right;" class="btns" onclick="location.href='/res/logout/'">로그아웃</button>
        <div class="logondiv" style="float: right; margin-right:10px;">
            <span>안녕하세요 {{ userid }} 님</span>
        </div>
        {% else %}
        <button style="float: right;" class="btns" onclick="location.href='/res/join/'" >회원가입</button>
        <button style="float: right; margin-top: 0px;" class="btns" form="logon">로그인</button>
        <form method='post' action="{% url 'res:logon' %}" id="logon" style="float: right;">
            {% csrf_token %}
            <label name="logonid">아이디:</label>
            <input type="text" name="logonid">
            <label name="logonpw">비밀번호:</label>
            <input type="password" name="logonpw">
       
        </form>
        {% endif %}
    </div>
    <!-- <button style="float: right;" class="btns" onclick="location.href='/res/index/'">글쓰기</button> -->
    <br>
    <div class="container">
        <a onclick="location.href='/res/index/0/'"><div class="main_item">맛보다</div></a>
        <div class="main_item">꾸미다</div></br>
        <div class="main_item2">배우다</div>
        <div class="main_item2">기타</div>
    </div>
</body>
</html>

templates/res/paging.html
<div class = "container mt-5">
    <ul class="pagination justify-content-center">
        <li class="page-item"><a class="page-link text-dark" href="javascript:goPage(0)">First</a></li>
        {% if commonPage.isPrev %}
            <li class="page-item"><a class="page-link text-dark" href="javascript:goPage({{commonPage.pre_page}})">Previous</a></li>
        {% endif %}

        {% for pg in commonPage.page_range %}
            {% if pg == commonPage.curPage %}
                <li class="page-item active" id="paging"><a class="page-link text-dark" href=javascript:goPage({{pg}}) style="border-color: gray; background-color: rgb(146, 147, 144)" ;>{{pg|add:1}}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link text-dark" href="javascript:goPage({{pg}})">{{pg|add:1}}</a></li>
            
            {% endif %}
        {%endfor%}
        
        
        {% if commonPage.isNext %}
            <li class="page-item"><a class="page-link text-dark" href="javascript:goPage({{commonPage.next_page}})">Next</a></li>
        {% endif %}

        <li class="page-item"><a class="page-link text-dark" href="javascript:goPage({{commonPage.totalPage}})">Last</a></li>
    </ul>
</div>

templates/res/res_detail.html
{% extends 'base.html' %}
{% block contents %}  
  
  <div style="float: right; margin: 10px;" class="logondiv">
              
    {% if userid %}
    <button style="float: right;" class="btns" onclick="location.href='/res/logout/'">로그아웃</button>
    <div class="logondiv" style="float: right; margin-right:10px;">
        <span>안녕하세요 {{ userid }} 님</span>
    </div>
    {% else %}
    
    
    <form method='post' action="{% url 'res:logon' %}" id="logon" style="float: right;">
        {% csrf_token %}
        <label name="logonid">아이디</label>
        <input type="text" name="logonid" >
        <label name="logonpw">비밀번호</label>
        <input type="password" name="logonpw" >
        <button style="float: right; margin: 5px;" class="btns" form="logon" >로그인</button>
        <button style="float: right;" class="btns" onclick="location.href='/res/join/'" ;>회원가입</button>
    </form>
    
    {% endif %}
  </div>
    
        <table class="eDetail">
          
        <div>
            <tbody>
                <tr>
                    <h1 style="text-align: center; margin-top: 90px;">{{resInfo.res_name}}</h1>
                </tr>
                <tr style="justify-content: center;">
                  <th>작성일</th>
                  <td>{{resInfo.res_wdate}}</td>
                  <th>조회수</th>
                  <td>{{resInfo.res_hit}}</td></br>x`
                  <th>위치</th>
                  <td>{{resInfo.res_locate}}</td>
                  <th>가격</th>
                  <td colspan="5">{{resList.res_item_price}}</td>
                </tr>
                <tr>
                  
                  <td colspan="5">{{resList.res_item_content|linebreaks}}</td>
                  <td colspan="5">{{resList.res_item_pic|linebreaks}}</td>
                  <!-- 이미지 데이터나 소개 -->
                  
                </tr>
               
            </tbody>

          
        </table>
    </div>
    
    <div class="container p-2 mt-5 border" >
        <table class="eReview"style="justify-content: center;">
                <th style="font-size: 1em;">메뉴</th>
              {% for menuItem in menuList %}
                <tr>
                <th>음식 메뉴</th>
                <td>{{menuItem.res_item_title}}</td>
                <th>음식 소개</th>
                <td>{{menuItem.res_item_content}}</td>
                <th>음식 가격</th>
                <td>{{menuItem.res_item_price}}</td>
                </tr>
              {% endfor %}
        </table>

    </div>

    <div class="container p-5 mt-5 border">
        <div class="review" style="margin-left: 200px;">
          <td><input type="text" class="res_review_title" placeholder="한줄평" style="width: 715px;margin-right: 18px;"></td>
          <th>별점</th>
          <td>
            <select name="score">
                <option value="1">1점</option>
                <option value="2">2점</option>
                <option value="3">3점</option>
                <option value="4">4점</option>
                <option value="5">5점</option>
            </select></br>
          </td>
            <br>
          <tr>
              <textarea class="form-control" id="res_review_content" name="review" style="border-style: solid; border-color: dimgray;"></textarea>
              <br>
              <button type="button" class="btn btn-sm bg-secondary btn-outline-dark text-bg-dark" id="btnList" style="float: right;">등록</button>
            </tr>
         </div>

        <div class="container p-2 mt-5 border" >
            <table class="eReview"style="justify-content: center;">
                  {% for review in reviewList %}
                    <th style="font-size: 1em;">후기</th>
                    <tr>
                    <th>작성자</th>
                    <td>{{review.mem_id}}</td>
                    <th>작성일</th>
                    <td>{{review.res_review_wdate}}</td>
                    <th>별점</th>
                    <td>{{review.res_review_rating}}</td>
                    <td colspan="5">{{review.res_review_content}}</td>
                    </tr>
                  {% endfor %}
            </table>
                  <!-- 리뷰 페이징: 자바스크립트로 다음 페이지가 보이게?(class name에 붙여서) -->
        </div>
    

    </div>
    
    <div class = "container mt-5" style = "text-align: right">    
          <button type="button" class="btn btn-primary bg-secondary btn-outline-dark text-bg-dark" id="btnList">목록</button>
          {% if memseq == resInfo.mem_seq %}
          <button class="btn btn-primary bg-secondary btn-outline-dark text-bg-dark" onclick="location.href='/res/deletepost/'; alert('게시글이 삭제되었습니다.')">게시글 삭제</button>
          {% endif %}
      </div>
          
<script>
    
  function goReview(pg)
  {
    
    location.href="/res/index/"+pg;


  }
$(document).ready( () => {
  $("#btnReview").click(() => {
    
    // $("#myform").prop("action", "/res/write");
    $("#myform").prop("method", "post");
    $("#myform").submit();
  });
})
</script>

{% endblock %}

templates/res/res_index.html
{% extends 'base.html' %}
{% block contents %}    


<div style="float: right; margin: 10px; padding: 5px; height: 70px;" class="logondiv">
            
    {% if userid %}
    <button style="float: right;" class="btns" onclick="location.href='/res/logout/'">로그아웃</button>
    <div class="logondiv" style="float: right; margin-right:10px;">
        <span>안녕하세요 {{ userid }} 님</span>
    </div>
    {% else %}
    <button style="float: right;" class="btns" onclick="location.href='/res/join/'" >회원가입</button>
    <button style="float: right; margin-top: 0px;" class="btns" form="logon">로그인</button>
    <form method='post' action="{% url 'res:logon' %}" id="logon" style="float: right;">
        {% csrf_token %}
        <label name="logonid">아이디</label>
        <input type="text" name="logonid">
        <label name="logonpw">비밀번호</label>
        <input type="password" name="logonpw">

    </form>
    {% endif %}
</div>
    
    


</div>
    
    <div class="container mt-3">
        <table class="eduList table table-striped">
            <colgroup>
                <col width="8%"/>
                <col width="35%"/>
                <col width="12%"/>
                <col width="8%"/>
                <col width="*%"/>
                <col width="8%"/>
            </colgroup>
            <thead>
                <tr style="text-align: center;">
                    <th>번호</th>
                    <th>학원명</th>
                    <th>작성자</th>
                    <th>평점</th>
                    <th>작성일</th>
                    <th>조회수</th>
                </tr>
            </thead>
            <tbody>
                {% for resItem in resList %}
                <tr style="text-align: center;">
                    <td>{{resItem.num}}</td>
                    <td><a href="/res/detail/{{resItem.res_seq}}/">{{resItem.res_name}}</a></td>
                    <td>{{resItem.mem_id}}</td>
                    <td>{{resItem.res_score}}</td>
                    <td>{{resItem.res_wdate}}</td>
                    <td>{{resItem.res_hit}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
    {% include "./paging.html" %}

    {% if userid %}
    <div class = "container mt-5" style = "text-align: right">    
        <div class="btn-group">
            <button type="button" class="btn btn-primary bg-secondary btn-outline-dark text-bg-dark " id="btnWrite">글쓰기</button>
            
        </div>
    </div>
    {% endif %}
    


    <script>

        function goPage(pg)
        {
          // 자바스크립트로 페이지 이동 - get방식으로 간단히 이동할 때
          location.href="/res/index/"+pg;
      
      
          // 이게 아닐 경우에는 form 태그 참조를 가져와서 사용한다
        }
      $(document).ready( () => {
        $("#btnWrite").click(() => {
          // 화살표 함수는 this 사용 못함
          $("#myform").prop("action", "/res/write");
          $("#myform").prop("method", "get");
          $("#myform").submit();
        });
      })
      </script>

{% endblock %}

templates/res/res_join_form.html
{% extends 'base.html' %}
{% block contents %}

    <form method="POST" action="{% url 'res:join_save' %}" id="signup">
        <fieldset>
      {% csrf_token %}
      <input type="hidden" name="idcheckyn" id="idcheckyn" value="N" >
      <div class="container mt-5">
    
        <div class="mb-3 mt-3">
          <label for="title" class="form-label" name="mem_id">사용자아이디:</label>
          <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Enter ID" name="mem_id"  id="mem_id">
            <button class="btn btn-secondary" type="button" id="btnIdCheck">중복체크</button>
          </div>
        </div>

        <div class="mb-3 mt-3">
          <label for="pwd" class="form-label">비밀번호:</label>
          <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pwd" required>
        </div>
        
        <div class="mb-3 mt-3">
          <label for="pwd2" class="form-label">비밀번호 확인:</label>
          <input type="password" class="form-control" id="pwd2" placeholder="Enter password" name="pwd2" required>
        </div>

        <div class="mb-3 mt-3">
          <label for="name" class="form-label">사용자이름:</label>
          <input type="text" class="form-control" id="mem_name" placeholder="Enter username" name="name" required>
        </div>
                      
          <div>회원유형</div>
          <label name="membertype">개인회원</label>
          <input type="radio" name="membertype" value="1" checked="checked">
          <label name="membertype">사장님회원</label>
          <input type="radio" name="membertype" value="2" onclick='return(false);'>      


        <div class="mb-3 mt-3">
          <label for="age" class="form-label">회원나이:</label>
          <input type="number" class="form-control" id="mem_age" placeholder="Enter age" name="age" required>
        </div>

      </div>
    </fieldset>

    </form>

    <div>
        <button class="btn btn-secondary" style="width:100px; float: right; margin-right: 150px;" form="signup">회원가입</button>
        <button class="btn btn-secondary" style="width:130px; float: right; margin-right: 5px;" onclick="location.href='/res/main/'">메인으로 이동</button>
    </div>

{%endblock%}

templates/res/res_write.html
{% extends 'base.html' %}
{% block contents %}

    
  <form method = "post" action = "{% url 'res:write_save' %}" id="writepost">
      {% csrf_token %}
    <div class = "container mt-5">
      <div  style='text-align:center; color:black;
      background-color: #ccc; font-weight:1000; height: 60px; line-height: 65px;'>게시글 작성</div>
      <div class="mb-3 mt-5">
        <label for="title" class="form-label">상호명</label>
        <input type="text" class="form-control" id="title" placeholder="name" name="title" required>
      </div>

      <div class="mb-3 mt-4">
        <label for="title" class="form-label">위치</label>
        <input type="text" class="form-control" id="title" placeholder="location" name="title" required>
      </div>

      <div class="mb-3 mt-4">
        <label for="title" class="form-label">연락처</label>
        <input type="text" class="form-control" id="title" placeholder="tel" name="title" required>
      </div>
      
      <div class="mb-3 mt-3">
        <label for="title" class="form-label">내용</label>
        <textarea class="form-control" rows="10" id="contents" name="contents" ></textarea></br>
      </div>

    </div>
  </form>
  <button class="btn btn-secondary" id="btnWrite" style="float: right; margin: 10px;" form="writepost">저장</button>
  <button class="btn btn-secondary" id="btnWrite" style="float: right; margin: 10px;">사진 첨부</button>

{% endblock %}